# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 991eceeccc8b80e746678c939b957425bec09bee981a5f136e208446decce26d6199cb5aa2309a5b012fa726f6a682a0e16ea69c38fa36f3dde4d150f6daacbf

test:
  secret_key_base: 2a3822e3f12e25ae60467d0139ddfbba4786b8e897713cf86a81892ffe01a1e79ad9b0c349c1faf570bae258ba4d64adb96b2e3210d3fcdea3d099b8cbe9ab8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
